apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: airship-software-deploy-chart-b3
  namespace: argo-armada-examples
spec:
  serviceAccountName: armada
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    script:
      command:
      - /bin/sh
      image: docker.io/seaneagan/airship-armada:chart_entrypoint-ubuntu_bionic
      source: |
        set -x
        RELEASE_PREFIX=argo-armada-examples
        armada apply_chart --release-prefix=$RELEASE_PREFIX /tmp/chart/doc
      volumeMounts:
        - name: chart
          mountPath: "/tmp/chart"
          readOnly: true
  volumes:
    - name: chart
      secret:
        secretName: airship-software-deploy-chart-b3
---
apiVersion: v1
kind: Secret
metadata:
  namespace: argo-armada-examples
  name: airship-software-deploy-chart-b3
type: Opaque
stringData:
  doc: |
    schema: "armada/Chart/v2"
    metadata:
      name: b3
      namespace: argo-armada-examples
    data:
      release: b3
      namespace: argo-armada-examples
      wait:
        timeout: 100
        labels:
          release_group: armada-b3
      source:
        location: https://kubernetes-charts-incubator.storage.googleapis.com/raw-0.2.3.tgz
        subpath: raw
        type: tar
      values:
        resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: b3
            data:
              chart: b3
