apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: airship-software-deploy-group-a
  namespace: argo-armada-examples
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
      - - templateRef:
            name: airship-software-deploy-chart
            template: entrypoint
          arguments:
            parameters:
              - name: namespace
                value: argo-armada-examples
              - name: name
                value: "{{item}}"
          withItems:
            - a1
            - a2
