#!/bin/bash

set -e

workflow_yaml_path=$1
workflow_yaml=$(cat "$workflow_yaml_path")

values=$(cat <<EOF
workflow:
$(echo "$workflow_yaml" | sed 's/^/  /')
EOF
)

values_file=$(mktemp)
echo "$values" > "$values_file"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Prefer plugin-local helm cli
PATH=$DIR:$PATH

# Generate workflow template
# `helm template` accepts release name differently in helm 2 vs 3
if helm version --client --short | grep -q "v3\."; then
  # helm 3 does schema validation as well
  helm template ignored $DIR/chart --values="$values_file"
else
  helm template --name ignored $DIR/chart --values="$values_file"
fi
