apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: armada-
  namespace: argo-armada
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      inputs:
        parameters:
          - name: name
      steps:
        - - name: call-template
            templateRef:
              name: "{{inputs.parameters.name}}"
              template: entrypoint
