#!/usr/bin/env bash

namespace=$1
workflow=$2

values=$(kubectl get armadaworkflows -n $namespace $workflow -o json | jq .spec)
values_file=$(mktemp)
echo "$values" > "$values_file"
argo_wf=$(helm template --name "$workflow" chart --values="$values_file")
echo "$argo_wf" | argo submit - --watch
