apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: armada-
  namespace: argo-armada
spec:
  entrypoint: entrypoint
  volumeClaimTemplates:
    - metadata:
        name: pulled-charts
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: converted-charts
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
  templates:
    - name: entrypoint
      inputs:
        parameters:
          - name: namespace
          - name: name
          - name: kubectl-image
          - name: generator-image
          - name: generator-config
      steps:
        - - name: call-template
            templateRef:
              name: armada-workflow
              template: entrypoint
            arguments:
              parameters:
                - name: namespace
                  value: "{{inputs.parameters.namespace}}"
                - name: name
                  value: "{{inputs.parameters.name}}"
                - name: kubectl-image
                  value: "{{inputs.parameters.kubectl-image}}"
                - name: generator-image
                  value: "{{inputs.parameters.generator-image}}"
                - name: generator-config
                  value: "{{inputs.parameters.generator-config}}"
