
{{- $envAll := . -}}
{{- $type_keys := list "dag" "groups" -}}
{{- $local := dict -}}
{{-  $_ := set $local "found_keys" list -}}
{{- range $key := $type_keys -}}
  {{- if not (empty (index $envAll.Values $key)) -}}
    {{-  $_ := set $local "found_keys" (append $local.found_keys $key) -}}
  {{- end -}}
{{- end -}}
{{- $type_key := index $local.found_keys 0 -}}
{{- $template := print "workflow_" $type_key -}}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ $envAll.Release.Name }}
spec:
  entrypoint: deploy
  volumeClaimTemplates:
    - metadata:
        name: converted
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
    -
{{ include "convert_template" $envAll | indent 6 }}
{{ include $template $envAll | indent 4 }}
    -
{{ include "task_template" $envAll | indent 6 }}
