resources:
  - github.com/seaneagan/argo-armada//base?ref=master
  - https://review.opendev.org/airship/armada//manifests?ref=refs/changes/67/706967/11
  - airship-software-deploy-chart.yaml
  - ../../common
  - ../../composites/a
  - ../../composites/b
  - ../../composites/c
  - airship-software-deploy.yaml
