apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: airship-software-deploy-group-c
  namespace: argo-armada-examples
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
      - - name: airship-software-deploy-chart-c1
          templateRef:
            name: airship-software-deploy-chart-c1
            template: entrypoint
