apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: armada-workflow
  namespace: argo-armada
spec:
  serviceAccountName: armada
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      inputs:
        parameters:
          - name: namespace
          - name: name
          - name: generator-image
          - name: generator-config
      steps:
        - - name: gen-argo-workflow-template
            template: gen-argo-workflow-template
            arguments:
              parameters:
                - name: namespace
                  value: "{{inputs.parameters.namespace}}"
                - name: name
                  value: "{{inputs.parameters.name}}"
                - name: image
                  value: "{{inputs.parameters.generator-image}}"
                - name: config
                  value: "{{inputs.parameters.generator-config}}"
        - - name: invoke-argo-workflow-template
            templateRef:
              name: "{{steps.gen-argo-workflow-template.outputs.result}}"
              template: entrypoint
              runtimeResolution: true
    - name: gen-argo-workflow-template
      inputs:
        parameters:
          - name: namespace
          - name: name
          - name: image
          - name: config
      script:
        image: "{{inputs.parameters.image}}"
        command: [/bin/sh]
        source: |
          argo-armada-generator "{{inputs.parameters.namespace}}" "{{inputs.parameters.name}}" '{{inputs.parameters.config}}'
