apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "armadaworkflows.armada.airshipit.org"
spec:
  group: "armada.airshipit.org"
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                task_template:
                  type: object
                  properties:
                    release_prefix:
                      type: string
                    container:
                      type: object
                      properties:
                        image:
                          type: string
                        command:
                          type:
                            array
                          items:
                            type: string
                dag:
                  type: array
                  items:
                    x-kubernetes-object-ref-api-version: armada.airshipit.org/v1alpha1
                    x-kubernetes-object-ref-kind: ArmadaChart
                    x-kubernetes-object-ref-name-key: name
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      dependencies:
                        x-kubernetes-object-ref-api-version: armada.airshipit.org/v1alpha1
                        x-kubernetes-object-ref-kind: ArmadaChart
                        x-kubernetes-object-ref-name-key: name
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          required:
                            - name
                    required:
                      - name
                groups:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      charts:
                        type: array
                        items:
                          x-kubernetes-object-ref-api-version: armada.airshipit.org/v1alpha1
                          x-kubernetes-object-ref-kind: ArmadaChart
                          x-kubernetes-object-ref-name-key: name
                          type: object
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          required:
                            - name
              oneOf:
                - required:
                  - dag
                - required:
                  - groups
  scope: "Namespaced"
  names:
    plural: "armadaworkflows"
    singular: "armadaworkflow"
    kind: "ArmadaWorkflow"
