apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: airship-software-deploy
  namespace: argo-armada-examples
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
      - - name: airship-software-deploy-group-a
          templateRef:
            name: airship-software-deploy-group-a
            template: entrypoint
      - - name: airship-software-deploy-group-b
          templateRef:
            name: airship-software-deploy-group-b
            template: entrypoint
      - - name: airship-software-deploy-group-c
          templateRef:
            name: airship-software-deploy-group-c
            template: entrypoint
