
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "armadacharts.armada.airshipit.org"
spec:
  group: "armada.airshipit.org"
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                release:
                  type: string
                namespace:
                  type: string
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dependencies:
                  type: array
                  items:
                    type: string
                protected:
                  type: object
                  properties:
                    continue_processing:
                      type: boolean
                test:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    timeout:
                      type: integer
                    options:
                      type: object
                      properties:
                        cleanup:
                          type: boolean
                wait:
                  type: object
                  properties:
                    timeout:
                      type: integer
                    # TODO: Find a way to allow this which works with k8s
                    #       structural schemas.
                    # resources_object:
                    #   type: object
                    #   additionalProperties:
                    #     oneOf:
                    #       - properties:
                    #           labels:
                    #             additionalProperties:
                    #               type: string
                    #           min_ready:
                    #             anyOf:
                    #               - type: integer
                    #               - type: string
                    #           required:
                    #             type: boolean
                    #       - type: array
                    #         items:
                    #           properties:
                    #             labels:
                    #               additionalProperties:
                    #                 type: string
                    #             min_ready:
                    #               anyOf:
                    #                 - type: integer
                    #                 - type: string
                    #             required:
                    #               type: boolean
                    resources:
                      type: array
                      items:
                        type: object
                        properties:
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          min_ready:
                            x-kubernetes-int-or-string: true
                            anyOf:
                              - type: integer
                              - type: string
                          required:
                            type: boolean
                          type:
                            type: string
                        required:
                          - type
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    native:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                source:
                  type: object
                  properties:
                    type:
                      type: string
                    location:
                      type: string
                    subpath:
                      type: string
                    reference:
                      type: string
                    proxy_server:
                      type: string
                    auth_method:
                      type: string
                  required:
                    - location
                    - type
                delete:
                  type: object
                  properties:
                    timeout:
                      type: integer
                upgrade:
                  type: object
                  properties:
                    pre:
                      type: object
                      properties:
                        delete:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                              labels:
                                type: object
                                additionalProperties:
                                  type: string
                            required:
                              - type
                    options:
                      type: object
                      properties:
                        force:
                          type: boolean
                        recreate_pods:
                          type: boolean
                        no_hooks:
                          type: boolean
              required:
                - namespace
                - release
                - source
  scope: "Namespaced"
  names:
    plural: "armadacharts"
    singular: "armadachart"
    kind: "ArmadaChart"
