
{{- $envAll := . -}}
{{- $type_keys := list "dag" "groups" -}}
{{- $local := dict -}}
{{- $workflow := $envAll.Values.workflow -}}
{{-  $_ := set $local "found_keys" list -}}
{{- range $key := $type_keys -}}
  {{- if not (empty (index $workflow.spec $key)) -}}
    {{-  $_ := set $local "found_keys" (append $local.found_keys $key) -}}
  {{- end -}}
{{- end -}}
{{- $type_key := index $local.found_keys 0 -}}
{{- $apply_charts_templates := print "apply_charts_templates_" $type_key -}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ $envAll.Values.argo_workflow_prefix }}{{ $workflow.metadata.name }}
spec:
{{- if $envAll.Values.serviceAccountName }}
  serviceAccountName: {{ $envAll.Values.serviceAccountName }}
{{- end }}
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: pull-charts
            template: pull-charts
        - - name: convert-charts
            template: convert-charts
        - - name: apply-charts
            template: apply-charts
    - name: apply-charts
{{ include $apply_charts_templates $envAll | indent 4 }}
    - name: pull-charts
{{ include "pull_charts_template" $envAll | indent 6 }}
    - name: convert-charts
{{ include "convert_charts_template" $envAll | indent 6 }}
    - name: apply-chart
{{ include "apply_chart_template" $envAll | indent 6 }}
