apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: armada-controller
  labels:
    rbac.armada.airshipit.org/aggregate-to-armada: "true"
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - armada.process
    resources:
      - locks
    verbs:
      - get
      - list
      - create
      - delete
      - patch
  - apiGroups:
      - armada.airshipit.org
    resources:
      - armadacharts
    verbs:
      - get
      - list
---
# Rules needed for the static workflow template
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: armada-workflow-static
  labels:
    rbac.armada.airshipit.org/aggregate-to-armada: "true"
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      # apply needs all of these
      - get
      - create
      - patch
  - apiGroups:
      - armada.airshipit.org
    resources:
      - armadaworkflows
    verbs:
      - get
      - list
---
# Taken from: https://github.com/argoproj/argo/blob/master/docs/workflow-rbac.md
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow
  labels:
    rbac.armada.airshipit.org/aggregate-to-armada: "true"
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
# Aggregate above roles into one for convenience
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: armada
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.armada.airshipit.org/aggregate-to-armada: "true"
rules: []
