apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: airship-software-deploy-group-b
  namespace: argo-armada-examples
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
      - - name: airship-software-deploy-chart-b1
          templateRef:
            name: airship-software-deploy-chart-b1
            template: entrypoint
        - name: airship-software-deploy-chart-b2
          templateRef:
            name: airship-software-deploy-chart-b2
            template: entrypoint
        - name: airship-software-deploy-chart-b3
          templateRef:
            name: airship-software-deploy-chart-b3
            template: entrypoint
