apiVersion: v1
kind: ServiceAccount
metadata:
  name: armada
  namespace: argo-armada-examples
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: armada-armada
subjects:
  - kind: ServiceAccount
    name: armada
    namespace: argo-armada-examples
roleRef:
  kind: ClusterRole
  name: armada
  apiGroup: rbac.authorization.k8s.io
